sudo: required
services:
- docker
before_install:
- docker build -t luccasmmg/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true luccasmmg/react-test npm test -- --coverage
after_success:
- docker build -t luccasmmg/multi-client ./client
- docker build -t luccasmmg/multi-nginx ./nginx
- docker build -t luccasmmg/multi-server ./server
- docker build -t luccasmmg/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push luccasmmg/multi-client
- docker push luccasmmg/multi-nginx
- docker push luccasmmg/multi-server
- docker push luccasmmg/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-821626484152
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: dxFFxAx1nk+wuym6Z/4EvxIV8INb1NgmgxM0MgHLqTe+eLuyteMIiCkKKIBGOgtaUZtyoLuiMHSRKcVHSz5JlbBCbVMuhpCvCKGdPvIfeDCZ9M9qAkQbJXRM9aYc7gL09fO9d/KCVswCbif9yLTORjHUtfxdoIpxlj5YlRZ/KT/FOAPnNgR528O0/ldIQ4fQz2wMxMkzAjw80X2CCSaKZty1dtI7dUqPZdilB2DguwDCcxAAYmJMkap/UV4gpja+EhujWyPaEweYhWkr81i8mmnNJ71/Nz3xPrV7MAtoAvLWF5oxlNxDBPDJdFzBooVzW4JlcUYY+luBzK0OIJ+qg3kJmJnlhww/7hsUBeaos37I2LUcLDFxJQGc18pkmIMcVCpJ/T53/fPjE+LxmTklmodpfuBW6DPoul2wyDW62leUHNJVOlm9Hoy/WAhBQzd0jNvW6usLDwWHC3fA4LMEAo3Fpj8VB4TdM8Ybx2g6gJn+dDts72XAlDiNMb7/dYgM6h7MZOSL41WhN66XMK43P0xY+5vSaDvRA34XAhxpUXlbM07ni5QMv3cDh5lo9Qk/sflk68WXJqRKyZ8JNK959SI0Ps2sukXiruZaM/jZAgE77hOP4YZzms+ioYAYyPD98yBuUKjIWF1suH4KJJBqMHhgZ15cwGt7ZnVChSIWkBw=
  secret_access_key:
    secure: dgY/aCHyLM2X2Tev2jPKOkMHkeRBw7bVWQPLst9004z3idR5M+gAN/wm/WiqqBi0m0jJe1+VaMeZXi2qcC7GsDmRdlIR8rgmweLv+WhYomgqo/lWngre7CBPQEBjMMPAdapcRF048mgS8Ptl5xbUpoyY6V0XFqdcQVpZFQPgCYHym03IBqzWxMn/avZ/FLJLtx9AucqOQ+KO6qKw5jt+wYgm+DpHPiWmWQQRBJK9ufdfweqsgyJqNpYOGINZBi7t9Q9zFpDKhX9PUWtKS7aMGqY64ysecbcbUJWiKZinlpA1ra1knnKxWbgpEOMr64L9A9SkU0TonqpL6/j+KAcx+yuzcKtsVSx1XSzk8P0He9TV26eSp/iPtUkyYU240M4JEgP7amJyEv81BPSH4X+Xr9u3FY/KLEm4ahtIJw8pDffN3ZQl4kSBygo9xsOPIxkHUAQYSaSY2IasYpsnRcMqkKRl8NZS7utjchK09O6PsozGkB5uVulXpNWNbUxFrJGBYCJglWhyG1NuunIkSZjQuCC6lXpgosDdJT77Mvpdk/idBhPr21hm1krhnlWfZ+YWqLBGchRD/fPwqKt8Sh+C+ia7i0z3V9fEtYHzKHq0nEoRtU97sVBIOiXp6TS/h+2PnQSivW/DMuHCgnPHtzAkJVOWHM1zrvUteiQ/1vVvJ2I=
